name: pyLOM Build CI
run-name: Building pyLOM on branch <${{ github.head_ref }}> to <${{ github.base_ref }}> by @${{ github.actor }}

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

defaults:
  run:
    shell: bash

jobs:    
  # Build SA3
  build_and_run_tests:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 16

    steps:
      - uses: actions/checkout@v3
      # Setup MPI and Python for this job
      - name: Setup MPI
        uses: mpi4py/setup-mpi@v1
        with:
          mpi: openmpi
      - name: Set up Python 3.8.5
        uses: actions/setup-python@v3
        with:
          python-version: 3.8.5
      # Run pyLOM compilation and deployment
      - name: Set up python dependencies
        run: make requirements
      - name: Fix h5py
        run: CC=mpicc HDF5_MPI="ON" pip install --no-binary=h5py h5py
      - name: Build compiled code
        run: make python
      - name: Install
        run: make install
